export const alertIndexParams = {
  index: 'alerts',
  body: {
    mappings: {
      properties: {
        publisherId: { type: 'keyword' },
        publisherPhoneNumber: { type: 'text' },
        publisherEmail: { type: 'text' },
        isFromAppUser: { type: 'boolean' },
        name: { type: 'text' },
        description: { type: 'text' },
        status: { type: 'keyword' },
        isModValidated: { type: 'boolean' },
        alertType: { type: 'text' },
        icadIdentifier: { type: 'text' },
        petType: { type: 'text' },
        specie: { type: 'text' },
        age: { type: 'integer' },
        ageExpressedIn: { type: 'text' },
        sex: { type: 'text' },
        breed: { type: 'text' },
        height: { type: 'text' },
        weight: { type: 'text' },
        hair: { type: 'text' },
        colors: { type: 'keyword' },
        imageUrls: { type: 'keyword' },
        hasTatoo: { type: 'boolean' },
        hasNecklace: { type: 'boolean' },
        necklaceMaterial: { type: 'text' },
        necklaceColor: { type: 'text' },
        hasMicrochip: { type: 'boolean' },
        isSterilized: { type: 'boolean' },
        location: {
          type: 'nested',
          properties: {
            country: { type: 'text' },
            city: { type: 'text' },
            address: { type: 'text' },
            postalCode: { type: 'text' },
            departmentName: { type: 'text' },
            departmentCode: { type: 'text' },
            coords: {
              type: 'object',
              properties: {
                latitude: { type: 'float' },
                longitude: { type: 'float' },
              },
            },
          },
        },
        date: { type: 'date' },
        isSuspicious: { type: 'boolean' },
        reward: { type: 'double' },
        createdAt: { type: 'date' },
        updatedAt: { type: 'date' },
      },
    },
  },
};
