version: "3"
services:
  # RABBITMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: ./gateway/.env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  # GATEWAY
  gateway:
    build:
      dockerfile: Dockerfile.dev
      context: ./gateway
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 8080:8080
    env_file:
      - ./gateway/.env
    volumes:
      - /usr/src/app/node_modules
      - ./gateway:/usr/src/app

  # ACCOUNT-SERVICE
  account-service:
    build:
      dockerfile: Dockerfile.dev
      context: ./account-service
    restart: always
    env_file:
      - ./account-service/.env
    depends_on:
      account-service-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - /usr/src/app/node_modules
      - ./account-service:/usr/src/app
  account-service-db:
    image: postgres:15.2
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./account-service/.env
    volumes:
      - ./db_dumps/account_service_dump/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 45s
      interval: 10s
      retries: 10

  # ALERT-SERVICE
  alert-service:
    build:
      dockerfile: Dockerfile.dev
      context: ./alert-service
    restart: always
    env_file:
      - ./alert-service/.env
    depends_on:
      alert-service-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - /usr/src/app/node_modules
      - ./alert-service:/usr/src/app
  alert-service-db:
    image: postgres:15.2
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./alert-service/.env
    volumes:
      - ./db_dumps/alert_service_dump/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 45s
      interval: 10s
      retries: 10

  # PET-ALERT-SCRAPER
  pet-alert-scraper:
    build:
      dockerfile: Dockerfile.dev
      context: ./pet-alert-scrapper
    restart: always
    ports:
      - 8086:3000
    volumes:
      - /usr/src/app/node_modules
      - ./pet-alert-scrapper:/usr/src/app
