# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #                     ELASTICSEARCH                   #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: elasticsearch-pvc
# spec:
#   storageClassName: elasticsearch-local-storage
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: elasticsearch-local-storage
# spec:
#   storageClassName: elasticsearch-local-storage
#   capacity:
#     storage: 8Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /mnt/volumes/elasticsearch-volume
#     type: DirectoryOrCreate
# ---    
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                     RABBITMQ                        #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  storageClassName: rabbitmq-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-local-storage
spec:
  storageClassName: rabbitmq-local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/volumes/rabbitmq-volume
    type: DirectoryOrCreate

---
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                ACCOUNT-SERVICE DATABASE             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-service-db-pvc
spec:
  storageClassName: account-service-db-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: account-service-db-local-storage
spec:
  storageClassName: account-service-db-local-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/volumes/account-service-db-volume
    type: DirectoryOrCreate

---
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                ALERT-SERVICE DATABASE             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alert-service-db-pvc
spec:
  storageClassName: alert-service-db-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alert-service-db-local-storage
spec:
  storageClassName: alert-service-db-local-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/volumes/alert-service-db-volume
    type: DirectoryOrCreate